version: '3.2'

services:
  eth-statediff-service:
    build:
      context: ./
      cache_from:
      - alpine:latest
      - golang:1.13
      dockerfile: ./Dockerfile
    environment:
    - VDB_COMMAND=serve
    volumes:
    - /local/geth/path:/app/geth/:ro
    - /tmp/somefile:/app/geth/chaindata/LOCK
    - ./environments/example.toml:/app/config.toml
    ports:
    - "127.0.0.1:8545:8545"

