[leveldb]
    path = "/app/geth-rw/chaindata"
    ancient = "/app/geth-rw/chaindata/ancient"

[server]
    ipcPath = "/app/test.ipc"
    httpPath = "127.0.0.1:8545"

[log]
    file = ""
    level = "info"

[eth]
    chainID = 1
